export const RECENT_ACTIVITY_LIKE_SUCCESS = 'RECENT_ACTIVITY_LIKE_SUCCESS';
export const RECENT_ACTIVITY_LIKE_ERROR = 'RECENT_ACTIVITY_LIKE_ERROR';

export const ACTIVITY_CAPTURE_SUCCESS = 'ACTIVITY_CAPTURE_SUCCESS';
export const ACTIVITY_CAPTURE_ERROR = 'ACTIVITY_CAPTURE_ERROR';

export const ACTIVITY_REMOVE_SUCCESS = 'ACTIVITY_REMOVE_SUCCESS';
export const ACTIVITY_REMOVE_ERROR = 'ACTIVITY_REMOVE_ERROR';
